### ISSUE TITLE
deprecate UT_Stub_CheckForceFail()

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/osal#737] opened 2021-01-05 16:57 UTC
With the deprecation of `UT_Stub_SetForceFail()`, its functionality was replaced with `UT_Stub_SetDefaultReturnValue()`.

The `UT_Stub_CheckForceFail()` should likewise be deprecated. 

https://github.com/nasa/osal/blob/d698a4d7ddc66826a4c7c287468b5f1aa6ca372f/ut_assert/inc/utstubs.h#L321

**Comment by skliper** [comment] 2021-02-17 20:19
Closing as duplicate of #823

**Closed** 2021-02-26 18:23 UTC
Labels: deprecate, unit-test
