### ISSUE TITLE
Access parameter in OS_makedir

### ISSUE THREAD

**Issue by astrogeco** [nasa/osal#1004] opened 2021-05-12 16:05 UTC
[CCB:2021-05-12](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-May-12-2021) APPROVED

_Originally posted by @astrogeco in https://github.com/nasa/osal/issues/998#issuecomment-839893908_

**Comment by skliper** [comment] 2021-05-12 19:51
Duplicate of #1005

**Closed** 2021-05-12 19:51 UTC
Labels: duplicate
