### ISSUE TITLE
Doxygen warning:  file argument matching multiple files

### ISSUE THREAD

**Issue by astrogeco** [nasa/osal#551] opened 2020-07-25 21:48 UTC
**Describe the bug**
Doxygen produces multiple ambiguous file warnings when building the documentation using `make doc` at the bundle level. For example:

```
/cfs/cFS/osal/src/os/posix/inc/os-impl-binsem.h:22: warning: the name `os-impl-binsem.h' supplied as the second argument in the \file statement matches the following input files:
   /cfs/cFS/osal/src/os/posix/inc/os-impl-binsem.h
   /cfs/cFS/osal/src/os/rtems/inc/os-impl-binsem.h
   /cfs/cFS/osal/src/os/vxworks/inc/os-impl-binsem.h
Please use a more specific name by including a (larger) part of the path!
```

See more warnings in this log
[warnings.log](https://github.com/nasa/osal/files/4976617/warnings.log)

**To Reproduce**
Checkout cFS bundle with submodules. 

Copy the `sample_defs` from cFE into the cfs root directory as well as the Makefile then

```
make prep
make doc
```

examine `cFS/build/doc/warnings.log`

**Expected behavior**
No warnings about multiple files

**Code snips**

This code 

```c
/**
 * \file     os-impl-binsem.h
 * \ingroup  rtems
 * \author   joseph.p.hickey@nasa.gov
 *
 */
```
can be replaced with
```c
/*!
 * \file     rtems/inc/os-impl-binsem.h
 * \ingroup  rtems
 * \author   joseph.p.hickey@nasa.gov
 *
 */
```

**System observed on:**
Ubuntu running on Docker 

**Additional context**
None

**Reporter Info**
Gerardo E. Cruz-Ortiz

**Comment by skliper** [comment] 2022-02-24 20:17
Duplicate of #1218, fixed in #1219

**Closed by skliper** 2022-02-24 20:17 UTC
Labels: docs
