### ISSUE TITLE
Add workflow to locally build osal documentation 

### ISSUE THREAD

**Issue by astrogeco** [nasa/osal#1054] opened 2021-05-26 16:29 UTC
**Is your feature request related to a problem? Please describe.**
Once https://github.com/nasa/osal/pull/1033 is merged we can now build the osalguide locally and check that PRs don't break the osal docs. 

**Describe the solution you'd like**
Create a "docs" workflow github actions workflow

**Describe alternatives you've considered**
Figure out how to trigger the cFS bundle workflows from OSAL PRs

**Additional context**
None

**Comment by skliper** [comment] 2021-06-04 16:20
Duplicate of #1036

**Closed by skliper** 2021-06-04 16:20 UTC
Labels: continuous-integration, docs, good first issue
